language: generic
sudo: false
cache:
  directories:
  - "$HOME/.racket"
env:
  global:
  - RACKET_DIR=~/racket
  - RACKET_VERSION=6.9
  - secure: PaPz/8T4GMRajN+2FcTDxcjHyyjnPN8P9wwvUcq38kvahyDEkzpi3dsuahZPBcNYkmHrD2ItoL8K2lOuFu1GNiaE368zrJPwS6Ae+bCvehc2boy1X+QG11SEkznoQ6Sxj7H5i/JUIOSUnTMeQ0vKPfWBpkFVNdCmZHFrW/5LM+LiutbMeSqQPRGLg5ZEf5hbb4sEpOGCKjxCFOCn7wlHe6WO39PZFaAm1rjEjbBKM8FVmXbQvnwtLa06W0wRSyB2ybgdW/5oxhVj71a4x5L2mCBmyKseYlu+nXiov8KQ24Ef5/1RfXZhZt8CqiFv6CKOAMQ8sMA4/8bVSzUt3GqoFBoJIIgS0VJr0j8HkflnT37r0WmGEvhTnnMswhYUc7dx8frZDTI7PkxXuiLpaHXU++/OHFd8WYncAPZCgV0FOSQd5cYAnzdT4OUu6xsXI7vPv98POH8GvpcjOsVOaAgmOEadkM2BMPma34XAs2s5PAIBXsPdKWOQxySe+fGej6Dnx76JAdfCwg41RcC2KJyBeCCtDo7G35cOPKVhsIGXvaTduusO5oMmHkf3/KC1fSG2sU/J6UX/daZrXeGr+5uoPJ3wBstGjMBPwWx3jYUaZJCWxkB/Lbni9yiyQnSq6Rej5cqMztBgUwRacQKlzqX6KIWFY2u8JoVmAvq/S38Zn8M=

before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- "./install-racket.sh"
- export PATH="${RACKET_DIR}/bin:${PATH}"
install:
- racket make.rkt && cd $TRAVIS_BUILD_DIR
script:
- echo 0
deploy:
  skip_cleanup: true
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
